[INFO][0][<module>] Linux dec2365 5.14.21-150400.24.46_12.0.73-cray_shasta_c #1 SMP Thu May 18 23:03:34 UTC 2023 (9c4698c) x86_64 x86_64
[INFO][0][<module>] /glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB (2.7)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl-2023a/lib/python3.9/site-packages/numpy (1.23.5)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl-2023a/lib/python3.9/site-packages/matplotlib (3.6.3)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl-2023a/lib/python3.9/site-packages/netCDF4 (1.6.2)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl-2023a/lib/python3.9/site-packages/cf_units (3.1.1)
[INFO][0][<module>] /glade/u/home/rfisher/.local/lib/python3.9/site-packages/sympy (1.12)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl-2023a/lib/python3.9/site-packages/mpi4py (3.1.4)
[INFO][0][<module>] 2023-09-14 13:19:24.855186
[DEBUG][1][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_VEGC] in the model results
[DEBUG][0][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_VEGC] in the model results
[DEBUG][1][WorkConfront][Biomass/Thurner][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][WorkConfront][Biomass/Tropical][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][1][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_VEGC] in the model results
[DEBUG][1][WorkConfront][Biomass/Thurner][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_VEGC] in the model results
[DEBUG][0][WorkConfront][Biomass/Tropical][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][1][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_VEGC] in the model results
[DEBUG][1][WorkConfront][Biomass/ESACCI][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_VEGC] in the model results
[DEBUG][0][WorkConfront][Biomass/GlobalCarbon][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][1][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_VEGC] in the model results
[DEBUG][1][WorkConfront][Biomass/ESACCI][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][1][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_FRACTION] in the model results
[DEBUG][1][WorkConfront][GrossPrimaryProductivity/FLUXNET2015][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_VEGC] in the model results
[DEBUG][0][WorkConfront][Biomass/GlobalCarbon][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][1][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_FRACTION] in the model results
[DEBUG][1][WorkConfront][GrossPrimaryProductivity/FLUXNET2015][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_VEGC] in the model results
[DEBUG][0][WorkConfront][Biomass/NBCD2000][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_VEGC] in the model results
[DEBUG][0][WorkConfront][Biomass/NBCD2000][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_VEGC] in the model results
[DEBUG][0][WorkConfront][Biomass/USForest][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_VEGC] in the model results
[DEBUG][0][WorkConfront][Biomass/USForest][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][3][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_FRACTION] in the model results
[DEBUG][3][WorkConfront][EcosystemRespiration/FLUXNET2015][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][2][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_FRACTION] in the model results
[DEBUG][2][WorkConfront][GrossPrimaryProductivity/WECANN][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][2][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_FRACTION] in the model results
[DEBUG][2][WorkConfront][GrossPrimaryProductivity/WECANN][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][6][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rsns,FSA] in the model results
[DEBUG][6][WorkConfront][SurfaceNetSWRadiation/GEWEX.SRB][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][6][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rsns,FSA] in the model results
[DEBUG][6][WorkConfront][SurfaceNetSWRadiation/WRMC.BSRN][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][7][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FIRE] in the model results
[DEBUG][7][WorkConfront][SurfaceNetLWRadiation/GEWEX.SRB][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][7][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FIRE] in the model results
[DEBUG][7][WorkConfront][SurfaceNetLWRadiation/WRMC.BSRN][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][4][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [hfls,le,EFLX_LH_TOT] in the model results
[DEBUG][4][WorkConfront][LatentHeat/DOLCE][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][5][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rsds,FSDS] in the model results
[DEBUG][5][WorkConfront][Albedo/CERES][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 157, in confront
    obs, mod, obs_timeint, mod_timeint = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 64, in stageData
    dn_mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][6][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rlus,FIRE] in the model results
[DEBUG][6][WorkConfront][SurfaceUpwardLWRadiation/CERESed4.1][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][6][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rlus,FIRE] in the model results
[DEBUG][6][WorkConfront][SurfaceUpwardLWRadiation/FLUXNET2015][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][3][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_FRACTION] in the model results
[DEBUG][3][WorkConfront][EcosystemRespiration/FLUXCOM][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][1][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_FRACTION] in the model results
[DEBUG][1][WorkConfront][GrossPrimaryProductivity/FLUXCOM][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][4][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [hfls,le,EFLX_LH_TOT] in the model results
[DEBUG][4][WorkConfront][LatentHeat/CLASS][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][2][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [lai,TLAI] in the model results
[DEBUG][2][WorkConfront][LeafAreaIndex/AVHRR][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][7][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FSDS] in the model results
[DEBUG][7][WorkConfront][SurfaceNetRadiation/CERESed4.1][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][7][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FSDS] in the model results
[DEBUG][7][WorkConfront][SurfaceNetRadiation/FLUXNET2015][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][4][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [hfls,le,EFLX_LH_TOT] in the model results
[DEBUG][4][WorkConfront][LatentHeat/WECANN][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][4][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [hfss,sh,FSH] in the model results
[DEBUG][4][WorkConfront][SensibleHeat/FLUXNET2015][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][2][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [lai,TLAI] in the model results
[DEBUG][2][WorkConfront][LeafAreaIndex/AVH15C1][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][6][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rlus,FIRE] in the model results
[DEBUG][6][WorkConfront][SurfaceUpwardLWRadiation/GEWEX.SRB][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][6][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rlus,FIRE] in the model results
[DEBUG][6][WorkConfront][SurfaceUpwardLWRadiation/WRMC.BSRN][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][3][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_FRACTION] in the model results
[DEBUG][3][WorkConfront][EcosystemRespiration/FLUXCOM][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][7][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FSDS] in the model results
[DEBUG][7][WorkConfront][SurfaceNetRadiation/GEWEX.SRB][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][7][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FSDS] in the model results
[DEBUG][7][WorkConfront][SurfaceNetRadiation/WRMC.BSRN][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][4][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [hfss,sh,FSH] in the model results
[DEBUG][4][WorkConfront][SensibleHeat/FLUXCOM][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][2][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [lai,TLAI] in the model results
[DEBUG][2][WorkConfront][LeafAreaIndex/MODIS][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][2][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_FRACTION] in the model results
[DEBUG][2][WorkConfront][NetEcosystemExchange/FLUXNET2015][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][2][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_FRACTION] in the model results
[DEBUG][2][WorkConfront][NetEcosystemExchange/FLUXNET2015][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][2][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_FRACTION] in the model results
[DEBUG][2][WorkConfront][EcosystemRespiration/FLUXNET2015][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][1][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_FRACTION] in the model results
[DEBUG][1][WorkConfront][GrossPrimaryProductivity/FLUXCOM][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][7][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FSDS] in the model results
[DEBUG][7][WorkConfront][SurfaceNetRadiation/CLASS][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][4][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [hfss,sh,FSH] in the model results
[DEBUG][4][WorkConfront][SensibleHeat/CLASS][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][5][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rsds,FSDS] in the model results
[DEBUG][5][WorkConfront][Albedo/GEWEX.SRB][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 157, in confront
    obs, mod, obs_timeint, mod_timeint = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 64, in stageData
    dn_mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][6][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FLDS] in the model results
[DEBUG][6][WorkConfront][SurfaceNetLWRadiation/CERESed4.1][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][6][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FLDS] in the model results
[DEBUG][6][WorkConfront][SurfaceNetLWRadiation/FLUXNET2015][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][4][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [hfss,sh,FSH] in the model results
[DEBUG][4][WorkConfront][SensibleHeat/WECANN][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][7][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [hfdsl,FGR12] in the model results
[DEBUG][7][WorkConfront][GroundHeatFlux/CLASS][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][5][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rsus,FSR] in the model results
[DEBUG][5][WorkConfront][SurfaceUpwardSWRadiation/CERESed4.1][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][5][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rsus,FSR] in the model results
[DEBUG][5][WorkConfront][SurfaceUpwardSWRadiation/FLUXNET2015][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][3][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [QVEGT] in the model results
[DEBUG][3][WorkConfront][Evapotranspiration/GLEAMv3.3a][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][3][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [QVEGT] in the model results
[DEBUG][3][WorkConfront][Evapotranspiration/MODIS][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][5][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rsus,FSR] in the model results
[DEBUG][5][WorkConfront][SurfaceUpwardSWRadiation/GEWEX.SRB][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][5][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rsus,FSR] in the model results
[DEBUG][5][WorkConfront][SurfaceUpwardSWRadiation/WRMC.BSRN][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][3][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [QVEGT] in the model results
[DEBUG][3][WorkConfront][Evapotranspiration/MOD16A2][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][3][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [hfls,le,EFLX_LH_TOT] in the model results
[DEBUG][3][WorkConfront][LatentHeat/FLUXNET2015][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][5][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rsns,FSA] in the model results
[DEBUG][5][WorkConfront][SurfaceNetSWRadiation/CERESed4.1][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][5][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rsns,FSA] in the model results
[DEBUG][5][WorkConfront][SurfaceNetSWRadiation/FLUXNET2015][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][3][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [hfls,le,EFLX_LH_TOT] in the model results
[DEBUG][3][WorkConfront][LatentHeat/FLUXCOM][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][6][modelPlots][SurfaceUpwardLWRadiation/FLUXNET2015][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][2][modelPlots][EcosystemRespiration/FLUXNET2015][RTM_ens38_case_3] Success
[INFO][5][modelPlots][SurfaceUpwardSWRadiation/WRMC.BSRN][RTM_ens38_case_3] Success
[INFO][0][modelPlots][Biomass/Tropical][RTM_ens38_case_3] Success
[INFO][5][modelPlots][SurfaceUpwardSWRadiation/WRMC.BSRN][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][1][modelPlots][GrossPrimaryProductivity/FLUXCOM][RTM_ens38_case_3] Success
[INFO][7][modelPlots][SurfaceNetRadiation/CERESed4.1][RTM_ens38_case_3] Success
[INFO][3][modelPlots][LatentHeat/FLUXCOM][RTM_ens38_case_3] Success
[INFO][0][modelPlots][Biomass/GlobalCarbon][RTM_ens38_case_3] Success
[INFO][2][modelPlots][EcosystemRespiration/FLUXCOM][RTM_ens38_case_3] Success
[INFO][6][modelPlots][SurfaceUpwardLWRadiation/GEWEX.SRB][RTM_ens38_case_3] Success
