[INFO][0][<module>] Linux dec2332 5.14.21-150400.24.46_12.0.73-cray_shasta_c #1 SMP Thu May 18 23:03:34 UTC 2023 (9c4698c) x86_64 x86_64
[INFO][0][<module>] /glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB (2.7)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl-2023a/lib/python3.9/site-packages/numpy (1.23.5)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl-2023a/lib/python3.9/site-packages/matplotlib (3.6.3)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl-2023a/lib/python3.9/site-packages/netCDF4 (1.6.2)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl-2023a/lib/python3.9/site-packages/cf_units (3.1.1)
[INFO][0][<module>] /glade/u/home/rfisher/.local/lib/python3.9/site-packages/sympy (1.12)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl-2023a/lib/python3.9/site-packages/mpi4py (3.1.4)
[INFO][0][<module>] 2023-09-14 12:18:08.150418
[DEBUG][6][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rlus,FIRE] in the model results
[DEBUG][5][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rsus,FSR] in the model results
[DEBUG][6][WorkConfront][SurfaceUpwardLWRadiation/FLUXNET2015][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][5][WorkConfront][SurfaceUpwardSWRadiation/FLUXNET2015][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][1][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_FRACTION] in the model results
[DEBUG][1][WorkConfront][Biomass/Thurner][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_VEGC] in the model results
[DEBUG][0][WorkConfront][Biomass/Tropical][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][1][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_FRACTION] in the model results
[DEBUG][1][WorkConfront][Biomass/Thurner][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_VEGC] in the model results
[DEBUG][0][WorkConfront][Biomass/Tropical][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][1][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_FRACTION] in the model results
[DEBUG][1][WorkConfront][Biomass/ESACCI][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][1][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_FRACTION] in the model results
[DEBUG][1][WorkConfront][Biomass/ESACCI][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_VEGC] in the model results
[DEBUG][0][WorkConfront][Biomass/GlobalCarbon][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][1][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_FRACTION] in the model results
[DEBUG][1][WorkConfront][GrossPrimaryProductivity/FLUXNET2015][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][1][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_FRACTION] in the model results
[DEBUG][1][WorkConfront][GrossPrimaryProductivity/FLUXNET2015][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_VEGC] in the model results
[DEBUG][0][WorkConfront][Biomass/GlobalCarbon][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_VEGC] in the model results
[DEBUG][0][WorkConfront][Biomass/NBCD2000][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_VEGC] in the model results
[DEBUG][0][WorkConfront][Biomass/NBCD2000][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_VEGC] in the model results
[DEBUG][0][WorkConfront][Biomass/USForest][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_VEGC] in the model results
[DEBUG][0][WorkConfront][Biomass/USForest][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][2][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_GPP] in the model results
[DEBUG][2][WorkConfront][GrossPrimaryProductivity/WECANN][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][4][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [hfls,le,EFLX_LH_TOT] in the model results
[DEBUG][4][WorkConfront][LatentHeat/WECANN][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][4][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [hfss,sh,FSH] in the model results
[DEBUG][4][WorkConfront][SensibleHeat/FLUXNET2015][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][5][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rsus,FSR] in the model results
[DEBUG][5][WorkConfront][SurfaceUpwardSWRadiation/GEWEX.SRB][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][5][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rsus,FSR] in the model results
[DEBUG][5][WorkConfront][SurfaceUpwardSWRadiation/WRMC.BSRN][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][4][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [hfss,sh,FSH] in the model results
[DEBUG][4][WorkConfront][SensibleHeat/FLUXCOM][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][6][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rlus,FIRE] in the model results
[DEBUG][6][WorkConfront][SurfaceUpwardLWRadiation/GEWEX.SRB][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][6][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rlus,FIRE] in the model results
[DEBUG][6][WorkConfront][SurfaceUpwardLWRadiation/WRMC.BSRN][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][4][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [hfss,sh,FSH] in the model results
[DEBUG][4][WorkConfront][SensibleHeat/CLASS][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][5][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rsns,FSA] in the model results
[DEBUG][5][WorkConfront][SurfaceNetSWRadiation/CERESed4.1][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][5][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rsns,FSA] in the model results
[DEBUG][5][WorkConfront][SurfaceNetSWRadiation/FLUXNET2015][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][4][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [hfss,sh,FSH] in the model results
[DEBUG][4][WorkConfront][SensibleHeat/WECANN][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][2][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [lai,TLAI] in the model results
[DEBUG][2][WorkConfront][LeafAreaIndex/AVHRR][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][3][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_AUTORESP] in the model results
[DEBUG][3][WorkConfront][EcosystemRespiration/FLUXCOM][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][1][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_FRACTION] in the model results
[DEBUG][1][WorkConfront][GrossPrimaryProductivity/FLUXCOM][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][6][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FIRE] in the model results
[DEBUG][6][WorkConfront][SurfaceNetLWRadiation/CERESed4.1][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][6][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FIRE] in the model results
[DEBUG][6][WorkConfront][SurfaceNetLWRadiation/FLUXNET2015][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][2][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [lai,TLAI] in the model results
[DEBUG][2][WorkConfront][LeafAreaIndex/AVH15C1][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][5][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rsns,FSA] in the model results
[DEBUG][5][WorkConfront][SurfaceNetSWRadiation/GEWEX.SRB][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][5][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rsns,FSA] in the model results
[DEBUG][5][WorkConfront][SurfaceNetSWRadiation/WRMC.BSRN][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][2][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [lai,TLAI] in the model results
[DEBUG][2][WorkConfront][LeafAreaIndex/MODIS][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][4][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rsds,FSDS] in the model results
[DEBUG][4][WorkConfront][Albedo/CERES][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 157, in confront
    obs, mod, obs_timeint, mod_timeint = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 64, in stageData
    dn_mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][2][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_NEP] in the model results
[DEBUG][2][WorkConfront][NetEcosystemExchange/FLUXNET2015][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][2][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_NEP] in the model results
[DEBUG][2][WorkConfront][NetEcosystemExchange/FLUXNET2015][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][2][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_AUTORESP] in the model results
[DEBUG][2][WorkConfront][EcosystemRespiration/FLUXNET2015][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][2][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_AUTORESP] in the model results
[DEBUG][2][WorkConfront][EcosystemRespiration/FLUXNET2015][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][5][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rlus,FIRE] in the model results
[DEBUG][5][WorkConfront][SurfaceUpwardLWRadiation/CERESed4.1][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][6][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FIRE] in the model results
[DEBUG][6][WorkConfront][SurfaceNetLWRadiation/GEWEX.SRB][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][6][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FIRE] in the model results
[DEBUG][6][WorkConfront][SurfaceNetLWRadiation/WRMC.BSRN][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][3][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_AUTORESP] in the model results
[DEBUG][3][WorkConfront][EcosystemRespiration/FLUXCOM][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][1][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_FRACTION] in the model results
[DEBUG][1][WorkConfront][GrossPrimaryProductivity/FLUXCOM][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][1][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_FRACTION] in the model results
[DEBUG][1][WorkConfront][GrossPrimaryProductivity/WECANN][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][6][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FIRE] in the model results
[DEBUG][6][WorkConfront][SurfaceNetRadiation/CERESed4.1][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][6][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FIRE] in the model results
[DEBUG][6][WorkConfront][SurfaceNetRadiation/FLUXNET2015][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][3][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [QVEGE] in the model results
[DEBUG][3][WorkConfront][Evapotranspiration/GLEAMv3.3a][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][3][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [QVEGE] in the model results
[DEBUG][3][WorkConfront][Evapotranspiration/MODIS][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][4][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rsds,FSDS] in the model results
[DEBUG][4][WorkConfront][Albedo/GEWEX.SRB][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 157, in confront
    obs, mod, obs_timeint, mod_timeint = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 64, in stageData
    dn_mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][4][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rsus,FSR] in the model results
[DEBUG][4][WorkConfront][SurfaceUpwardSWRadiation/CERESed4.1][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][3][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [QVEGE] in the model results
[DEBUG][3][WorkConfront][Evapotranspiration/MOD16A2][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][3][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [hfls,le,EFLX_LH_TOT] in the model results
[DEBUG][3][WorkConfront][LatentHeat/FLUXNET2015][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][3][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [hfls,le,EFLX_LH_TOT] in the model results
[DEBUG][3][WorkConfront][LatentHeat/FLUXCOM][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][3][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [hfls,le,EFLX_LH_TOT] in the model results
[DEBUG][3][WorkConfront][LatentHeat/DOLCE][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][3][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [hfls,le,EFLX_LH_TOT] in the model results
[DEBUG][3][WorkConfront][LatentHeat/CLASS][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][7][MakeComparable][SurfaceNetRadiation/GEWEX.SRB][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Spatial data was clipped from the reference:  before: [288 360 720] after: [288 360 711]
[INFO][7][AnalysisMeanStateSpace][rns] Bias scored using Collier2018
[INFO][7][AnalysisMeanStateSpace][rns] RMSE scored using Collier2018
[INFO][7][confront][SurfaceNetRadiation/GEWEX.SRB][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][7][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FIRE] in the model results
[DEBUG][7][WorkConfront][SurfaceNetRadiation/GEWEX.SRB][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][7][AnalysisMeanStateSites][rns] Bias scored using Collier2018
[INFO][7][AnalysisMeanStateSites][rns] RMSE scored using Collier2018
[INFO][7][confront][SurfaceNetRadiation/WRMC.BSRN][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][7][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FIRE] in the model results
[DEBUG][7][WorkConfront][SurfaceNetRadiation/WRMC.BSRN][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][7][MakeComparable][SurfaceNetRadiation/CLASS][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Spatial data was clipped from the reference:  before: [ 84 360 720] after: [ 84 360 711]
[INFO][7][AnalysisMeanStateSpace][rns] Bias scored using Collier2018
[INFO][7][AnalysisMeanStateSpace][rns] RMSE scored using Collier2018
[INFO][7][confront][SurfaceNetRadiation/CLASS][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][7][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FIRE] in the model results
[DEBUG][7][WorkConfront][SurfaceNetRadiation/CLASS][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][7][MakeComparable][GroundHeatFlux/CLASS][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Spatial data was clipped from the reference:  before: [ 84 360 720] after: [ 84 360 711]
[INFO][7][AnalysisMeanStateSpace][hfdsl] Bias scored using Collier2018
[INFO][7][AnalysisMeanStateSpace][hfdsl] RMSE scored using Collier2018
[INFO][7][confront][GroundHeatFlux/CLASS][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][7][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [hfdsl,FGR12] in the model results
[DEBUG][7][WorkConfront][GroundHeatFlux/CLASS][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][6][modelPlots][SurfaceUpwardLWRadiation/FLUXNET2015][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][2][modelPlots][EcosystemRespiration/FLUXNET2015][RTM_ens38_case_3] Success
[INFO][5][modelPlots][SurfaceUpwardSWRadiation/WRMC.BSRN][RTM_ens38_case_3] Success
[INFO][0][modelPlots][Biomass/Tropical][RTM_ens38_case_3] Success
[INFO][7][modelPlots][SurfaceNetRadiation/CERESed4.1][RTM_ens38_case_3] Success
[INFO][3][modelPlots][LatentHeat/FLUXCOM][RTM_ens38_case_3] Success
[INFO][5][modelPlots][SurfaceUpwardSWRadiation/WRMC.BSRN][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][1][modelPlots][GrossPrimaryProductivity/FLUXCOM][RTM_ens38_case_3] Success
[INFO][0][modelPlots][Biomass/GlobalCarbon][RTM_ens38_case_3] Success
[INFO][6][modelPlots][SurfaceUpwardLWRadiation/GEWEX.SRB][RTM_ens38_case_3] Success
[INFO][4][modelPlots][SensibleHeat/CLASS][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][2][modelPlots][EcosystemRespiration/FLUXCOM][RTM_ens38_case_3] Success
[INFO][1][modelPlots][GrossPrimaryProductivity/WECANN][RTM_ens38_case_3] Success
[INFO][0][modelPlots][Biomass/NBCD2000][RTM_ens38_case_3] Success
[INFO][5][modelPlots][SurfaceNetSWRadiation/CERESed4.1][RTM_ens38_case_3] Success
[INFO][4][modelPlots][SensibleHeat/WECANN][RTM_ens38_case_3] Success
[INFO][7][modelPlots][SurfaceNetRadiation/CERESed4.1][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][3][modelPlots][LatentHeat/FLUXCOM][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][6][modelPlots][SurfaceUpwardLWRadiation/GEWEX.SRB][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][2][modelPlots][Evapotranspiration/GLEAMv3.3a][RTM_ens38_case_3] Success
[INFO][7][modelPlots][SurfaceNetRadiation/FLUXNET2015][RTM_ens38_case_3] Success
[INFO][1][modelPlots][LeafAreaIndex/AVHRR][RTM_ens38_case_3] Success
[INFO][0][modelPlots][Biomass/USForest][RTM_ens38_case_3] Success
[INFO][4][modelPlots][SensibleHeat/WECANN][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][6][modelPlots][SurfaceUpwardLWRadiation/WRMC.BSRN][RTM_ens38_case_3] Success
[INFO][3][modelPlots][LatentHeat/DOLCE][RTM_ens38_case_3] Success
[INFO][7][modelPlots][SurfaceNetRadiation/FLUXNET2015][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][0][modelPlots][Biomass/Thurner][RTM_ens38_case_3] Success
[DEBUG][0][WorkPost][Biomass/ESACCI][RTM_ens38_case_3]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 616, in WorkPost
    c.modelPlots(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 948, in modelPlots
    ax = var.plot(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Variable.py", line 1370, in plot
    self.lon_bnds[lon_empty[0], 0],
IndexError: index 0 is out of bounds for axis 0 with size 0

[INFO][6][modelPlots][SurfaceUpwardLWRadiation/WRMC.BSRN][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][5][modelPlots][SurfaceNetSWRadiation/CERESed4.1][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][0][modelPlots][GrossPrimaryProductivity/FLUXNET2015][RTM_ens38_case_3] Success
[INFO][4][modelPlots][Albedo/CERES][RTM_ens38_case_3] Success
[INFO][5][modelPlots][SurfaceNetSWRadiation/FLUXNET2015][RTM_ens38_case_3] Success
[INFO][2][modelPlots][Evapotranspiration/GLEAMv3.3a][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][7][modelPlots][SurfaceNetRadiation/GEWEX.SRB][RTM_ens38_case_3] Success
[INFO][1][modelPlots][LeafAreaIndex/AVHRR][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][5][modelPlots][SurfaceNetSWRadiation/FLUXNET2015][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][6][modelPlots][SurfaceNetLWRadiation/CERESed4.1][RTM_ens38_case_3] Success
[INFO][3][modelPlots][LatentHeat/DOLCE][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][4][modelPlots][Albedo/CERES][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][5][modelPlots][SurfaceNetSWRadiation/GEWEX.SRB][RTM_ens38_case_3] Success
[INFO][1][modelPlots][LeafAreaIndex/AVH15C1][RTM_ens38_case_3] Success
[INFO][2][modelPlots][Evapotranspiration/MODIS][RTM_ens38_case_3] Success
[INFO][3][modelPlots][LatentHeat/CLASS][RTM_ens38_case_3] Success
[INFO][7][modelPlots][SurfaceNetRadiation/GEWEX.SRB][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][6][modelPlots][SurfaceNetLWRadiation/CERESed4.1][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][7][modelPlots][SurfaceNetRadiation/WRMC.BSRN][RTM_ens38_case_3] Success
[INFO][4][modelPlots][Albedo/GEWEX.SRB][RTM_ens38_case_3] Success
[INFO][6][modelPlots][SurfaceNetLWRadiation/FLUXNET2015][RTM_ens38_case_3] Success
[INFO][7][modelPlots][SurfaceNetRadiation/WRMC.BSRN][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][5][modelPlots][SurfaceNetSWRadiation/GEWEX.SRB][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][1][modelPlots][LeafAreaIndex/AVH15C1][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][6][modelPlots][SurfaceNetLWRadiation/FLUXNET2015][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][2][modelPlots][Evapotranspiration/MODIS][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][3][modelPlots][LatentHeat/CLASS][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][5][modelPlots][SurfaceNetSWRadiation/WRMC.BSRN][RTM_ens38_case_3] Success
[INFO][3][modelPlots][LatentHeat/WECANN][RTM_ens38_case_3] Success
[INFO][5][modelPlots][SurfaceNetSWRadiation/WRMC.BSRN][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][7][modelPlots][SurfaceNetRadiation/CLASS][RTM_ens38_case_3] Success
[INFO][4][modelPlots][Albedo/GEWEX.SRB][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][1][modelPlots][LeafAreaIndex/MODIS][RTM_ens38_case_3] Success
[INFO][6][modelPlots][SurfaceNetLWRadiation/GEWEX.SRB][RTM_ens38_case_3] Success
[INFO][2][modelPlots][Evapotranspiration/MOD16A2][RTM_ens38_case_3] Success
[INFO][3][modelPlots][LatentHeat/WECANN][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][5][modelPlots][SurfaceUpwardLWRadiation/CERESed4.1][RTM_ens38_case_3] Success
[INFO][4][modelPlots][SurfaceUpwardSWRadiation/CERESed4.1][RTM_ens38_case_3] Success
[INFO][3][modelPlots][SensibleHeat/FLUXNET2015][RTM_ens38_case_3] Success
[INFO][7][modelPlots][SurfaceNetRadiation/CLASS][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][3][modelPlots][SensibleHeat/FLUXNET2015][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][1][modelPlots][LeafAreaIndex/MODIS][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][2][modelPlots][Evapotranspiration/MOD16A2][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][6][modelPlots][SurfaceNetLWRadiation/GEWEX.SRB][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][1][modelPlots][NetEcosystemExchange/FLUXNET2015][RTM_ens38_case_3] Success
[INFO][2][modelPlots][LatentHeat/FLUXNET2015][RTM_ens38_case_3] Success
[INFO][7][modelPlots][GroundHeatFlux/CLASS][RTM_ens38_case_3] Success
[INFO][6][modelPlots][SurfaceNetLWRadiation/WRMC.BSRN][RTM_ens38_case_3] Success
[INFO][5][modelPlots][SurfaceUpwardLWRadiation/CERESed4.1][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][4][modelPlots][SurfaceUpwardSWRadiation/CERESed4.1][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][3][modelPlots][SensibleHeat/FLUXCOM][RTM_ens38_case_3] Success
[INFO][6][modelPlots][SurfaceNetLWRadiation/WRMC.BSRN][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][2][modelPlots][LatentHeat/FLUXNET2015][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][4][modelPlots][SurfaceUpwardSWRadiation/FLUXNET2015][RTM_ens38_case_3] Success
[INFO][5][modelPlots][SurfaceUpwardLWRadiation/FLUXNET2015][RTM_ens38_case_3] Success
[INFO][4][modelPlots][SurfaceUpwardSWRadiation/FLUXNET2015][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][7][modelPlots][GroundHeatFlux/CLASS][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][3][modelPlots][SensibleHeat/FLUXCOM][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][4][modelPlots][SurfaceUpwardSWRadiation/GEWEX.SRB][RTM_ens38_case_3] Success
[INFO][3][modelPlots][SensibleHeat/CLASS][RTM_ens38_case_3] Success
[INFO][4][modelPlots][SurfaceUpwardSWRadiation/GEWEX.SRB][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][3][<module>][process time] 58.9 s
[INFO][7][<module>][process time] 3353.6 s
[INFO][5][<module>][process time] 49.6 s
[INFO][4][<module>][process time] 62.9 s
[INFO][1][<module>][process time] 46.0 s
[INFO][0][<module>][process time] 18.9 s
[INFO][2][<module>][process time] 48.7 s
[INFO][6][<module>][process time] 48.7 s
[INFO][0][<module>][total time] 3455.5 s
[INFO][0][<module>][process balance] 177.56
[INFO][0][<module>][parallel efficiency] 13%
