[INFO][0][<module>] Linux dec2206 5.14.21-150400.24.46_12.0.73-cray_shasta_c #1 SMP Thu May 18 23:03:34 UTC 2023 (9c4698c) x86_64 x86_64
[INFO][0][<module>] /glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB (2.7)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl-2023a/lib/python3.9/site-packages/numpy (1.23.5)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl-2023a/lib/python3.9/site-packages/matplotlib (3.6.3)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl-2023a/lib/python3.9/site-packages/netCDF4 (1.6.2)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl-2023a/lib/python3.9/site-packages/cf_units (3.1.1)
[INFO][0][<module>] /glade/u/home/rfisher/.local/lib/python3.9/site-packages/sympy (1.12)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl-2023a/lib/python3.9/site-packages/mpi4py (3.1.4)
[INFO][0][<module>] 2023-09-14 10:17:44.348694
[DEBUG][1][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_GPP] in the model results
[DEBUG][1][WorkConfront][GrossPrimaryProductivity/FLUXNET2015][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_FRACTION] in the model results
[DEBUG][0][WorkConfront][Biomass/Tropical][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_FRACTION] in the model results
[DEBUG][0][WorkConfront][Biomass/Tropical][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_FRACTION] in the model results
[DEBUG][0][WorkConfront][Biomass/GlobalCarbon][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_FRACTION] in the model results
[DEBUG][0][WorkConfront][Biomass/GlobalCarbon][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][7][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FIRE] in the model results
[DEBUG][7][WorkConfront][SurfaceNetLWRadiation/WRMC.BSRN][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_FRACTION] in the model results
[DEBUG][0][WorkConfront][Biomass/NBCD2000][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_FRACTION] in the model results
[DEBUG][0][WorkConfront][Biomass/NBCD2000][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_FRACTION] in the model results
[DEBUG][0][WorkConfront][Biomass/USForest][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_FRACTION] in the model results
[DEBUG][0][WorkConfront][Biomass/USForest][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_FRACTION] in the model results
[DEBUG][0][WorkConfront][Biomass/Thurner][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_FRACTION] in the model results
[DEBUG][0][WorkConfront][Biomass/Thurner][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_FRACTION] in the model results
[DEBUG][0][WorkConfront][Biomass/ESACCI][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_FRACTION] in the model results
[DEBUG][0][WorkConfront][Biomass/ESACCI][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_FRACTION] in the model results
[DEBUG][0][WorkConfront][GrossPrimaryProductivity/FLUXNET2015][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][4][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [hfss,sh,FSH] in the model results
[DEBUG][4][WorkConfront][SensibleHeat/CLASS][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][1][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_GPP] in the model results
[DEBUG][1][WorkConfront][GrossPrimaryProductivity/FLUXCOM][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][1][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_GPP] in the model results
[DEBUG][1][WorkConfront][GrossPrimaryProductivity/FLUXCOM][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][1][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_GPP] in the model results
[DEBUG][1][WorkConfront][GrossPrimaryProductivity/WECANN][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][1][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_GPP] in the model results
[DEBUG][1][WorkConfront][GrossPrimaryProductivity/WECANN][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][2][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_AUTORESP] in the model results
[DEBUG][2][WorkConfront][EcosystemRespiration/FLUXNET2015][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][4][MakeComparable][SensibleHeat/WECANN][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Spatial data was clipped from the reference:  before: [108 180 360] after: [108 180 356]
[DEBUG][2][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [HR] in the model results
[DEBUG][2][WorkConfront][EcosystemRespiration/FLUXNET2015][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][3][MakeComparable][LatentHeat/FLUXCOM][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Spatial data was clipped from the reference:  before: [420 360 720] after: [420 360 711]
[INFO][6][AnalysisMeanStateSites][rlus] Bias scored using Collier2018
[INFO][6][AnalysisMeanStateSites][rlus] RMSE scored using Collier2018
[INFO][6][confront][SurfaceUpwardLWRadiation/FLUXNET2015][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][6][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rlus,FIRE] in the model results
[DEBUG][6][WorkConfront][SurfaceUpwardLWRadiation/FLUXNET2015][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][5][AnalysisMeanStateSites][rsus] Bias scored using Collier2018
[INFO][5][AnalysisMeanStateSites][rsus] RMSE scored using Collier2018
[INFO][5][confront][SurfaceUpwardSWRadiation/WRMC.BSRN][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][5][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rsus,FSR] in the model results
[DEBUG][5][WorkConfront][SurfaceUpwardSWRadiation/WRMC.BSRN][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][4][AnalysisMeanStateSpace][hfss] Bias scored using Collier2018
[INFO][4][AnalysisMeanStateSpace][hfss] RMSE scored using Collier2018
[INFO][4][confront][SensibleHeat/WECANN][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][4][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [hfss,sh,FSH] in the model results
[DEBUG][4][WorkConfront][SensibleHeat/WECANN][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][1][MakeComparable][LeafAreaIndex/AVHRR][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Spatial data was clipped from the reference:  before: [348 360 720] after: [348 360 711]
[INFO][3][AnalysisMeanStateSpace][hfls] Bias scored using Collier2018
[INFO][3][AnalysisMeanStateSpace][hfls] RMSE scored using Collier2018
[INFO][3][confront][LatentHeat/FLUXCOM][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][3][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [hfls,le,EFLX_LH_TOT] in the model results
[DEBUG][3][WorkConfront][LatentHeat/FLUXCOM][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][1][AnalysisMeanStateSpace][lai] Bias scored using Collier2018
[INFO][1][AnalysisMeanStateSpace][lai] RMSE scored using Collier2018
[INFO][1][confront][LeafAreaIndex/AVHRR][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][1][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [lai,TLAI] in the model results
[DEBUG][1][WorkConfront][LeafAreaIndex/AVHRR][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][2][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_AUTORESP] in the model results
[DEBUG][2][WorkConfront][EcosystemRespiration/FLUXCOM][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][5][MakeComparable][SurfaceNetSWRadiation/CERESed4.1][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Spatial data was clipped from the reference:  before: [228 360 720] after: [228 360 711]
[INFO][6][MakeComparable][SurfaceUpwardLWRadiation/GEWEX.SRB][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Spatial data was clipped from the reference:  before: [288 360 720] after: [288 360 711]
[DEBUG][2][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [HR] in the model results
[DEBUG][2][WorkConfront][EcosystemRespiration/FLUXCOM][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][5][AnalysisMeanStateSpace][rsns] Bias scored using Collier2018
[INFO][6][AnalysisMeanStateSpace][rlus] Bias scored using Collier2018
[INFO][5][AnalysisMeanStateSpace][rsns] RMSE scored using Collier2018
[INFO][5][confront][SurfaceNetSWRadiation/CERESed4.1][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][5][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rsns,FSA] in the model results
[DEBUG][5][WorkConfront][SurfaceNetSWRadiation/CERESed4.1][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][6][AnalysisMeanStateSpace][rlus] RMSE scored using Collier2018
[INFO][6][confront][SurfaceUpwardLWRadiation/GEWEX.SRB][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][6][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rlus,FIRE] in the model results
[DEBUG][6][WorkConfront][SurfaceUpwardLWRadiation/GEWEX.SRB][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][3][MakeComparable][LatentHeat/DOLCE][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Spatial data was clipped from the reference:  before: [120 360 720] after: [120 360 711]
[INFO][1][MakeComparable][LeafAreaIndex/AVH15C1][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Spatial data was clipped from the reference:  before: [468 360 720] after: [468 360 711]
[INFO][3][AnalysisMeanStateSpace][hfls] Bias scored using Collier2018
[INFO][3][AnalysisMeanStateSpace][hfls] RMSE scored using Collier2018
[INFO][3][confront][LatentHeat/DOLCE][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][3][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [hfls,le,EFLX_LH_TOT] in the model results
[DEBUG][3][WorkConfront][LatentHeat/DOLCE][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][1][AnalysisMeanStateSpace][lai] Bias scored using Collier2018
[INFO][1][AnalysisMeanStateSpace][lai] RMSE scored using Collier2018
[INFO][1][confront][LeafAreaIndex/AVH15C1][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][1][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [lai,TLAI] in the model results
[DEBUG][1][WorkConfront][LeafAreaIndex/AVH15C1][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][4][AnalysisMeanStateSpace][albedo] Bias scored using Collier2018
[INFO][4][AnalysisMeanStateSpace][albedo] RMSE scored using Collier2018
[INFO][4][confront][Albedo/CERES][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][4][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rsds,FSDS] in the model results
[DEBUG][4][WorkConfront][Albedo/CERES][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 157, in confront
    obs, mod, obs_timeint, mod_timeint = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 64, in stageData
    dn_mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][6][AnalysisMeanStateSites][rlus] Bias scored using Collier2018
[INFO][6][AnalysisMeanStateSites][rlus] RMSE scored using Collier2018
[INFO][5][AnalysisMeanStateSites][rsns] Bias scored using Collier2018
[INFO][5][AnalysisMeanStateSites][rsns] RMSE scored using Collier2018
[INFO][6][confront][SurfaceUpwardLWRadiation/WRMC.BSRN][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][6][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rlus,FIRE] in the model results
[DEBUG][6][WorkConfront][SurfaceUpwardLWRadiation/WRMC.BSRN][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][5][confront][SurfaceNetSWRadiation/FLUXNET2015][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][5][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rsns,FSA] in the model results
[DEBUG][5][WorkConfront][SurfaceNetSWRadiation/FLUXNET2015][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][3][MakeComparable][LatentHeat/CLASS][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Spatial data was clipped from the reference:  before: [ 84 360 720] after: [ 84 360 711]
[INFO][1][MakeComparable][LeafAreaIndex/MODIS][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Spatial data was clipped from the reference:  before: [ 72 360 720] after: [ 72 360 711]
[INFO][3][AnalysisMeanStateSpace][hfls] Bias scored using Collier2018
[INFO][1][AnalysisMeanStateSpace][lai] Bias scored using Collier2018
[INFO][3][AnalysisMeanStateSpace][hfls] RMSE scored using Collier2018
[INFO][3][confront][LatentHeat/CLASS][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][3][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [hfls,le,EFLX_LH_TOT] in the model results
[DEBUG][3][WorkConfront][LatentHeat/CLASS][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][1][AnalysisMeanStateSpace][lai] RMSE scored using Collier2018
[INFO][1][confront][LeafAreaIndex/MODIS][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][1][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [lai,TLAI] in the model results
[DEBUG][1][WorkConfront][LeafAreaIndex/MODIS][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][1][extractTimeSeries][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Could not find [FATES_NEP] in the model results
[DEBUG][1][WorkConfront][NetEcosystemExchange/FLUXNET2015][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][1][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FATES_NEP] in the model results
[DEBUG][1][WorkConfront][NetEcosystemExchange/FLUXNET2015][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][7][MakeComparable][SurfaceNetRadiation/CERESed4.1][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Spatial data was clipped from the reference:  before: [228 360 720] after: [228 360 711]
[INFO][7][AnalysisMeanStateSpace][rns] Bias scored using Collier2018
[INFO][7][AnalysisMeanStateSpace][rns] RMSE scored using Collier2018
[INFO][7][confront][SurfaceNetRadiation/CERESed4.1][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][7][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FIRE] in the model results
[DEBUG][7][WorkConfront][SurfaceNetRadiation/CERESed4.1][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][5][MakeComparable][SurfaceNetSWRadiation/GEWEX.SRB][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Spatial data was clipped from the reference:  before: [288 360 720] after: [288 360 711]
[INFO][3][MakeComparable][LatentHeat/WECANN][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Spatial data was clipped from the reference:  before: [108 180 360] after: [108 180 356]
[INFO][2][MakeComparable][Evapotranspiration/GLEAMv3.3a][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Spatial data was clipped from the reference:  before: [468 360 720] after: [468 360 711]
[INFO][3][AnalysisMeanStateSpace][hfls] Bias scored using Collier2018
[INFO][3][AnalysisMeanStateSpace][hfls] RMSE scored using Collier2018
[INFO][3][confront][LatentHeat/WECANN][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][3][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [hfls,le,EFLX_LH_TOT] in the model results
[DEBUG][3][WorkConfront][LatentHeat/WECANN][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][5][AnalysisMeanStateSpace][rsns] Bias scored using Collier2018
[INFO][5][AnalysisMeanStateSpace][rsns] RMSE scored using Collier2018
[INFO][5][confront][SurfaceNetSWRadiation/GEWEX.SRB][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][5][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rsns,FSA] in the model results
[DEBUG][5][WorkConfront][SurfaceNetSWRadiation/GEWEX.SRB][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][2][AnalysisMeanStateSpace][et] Bias scored using Collier2018
[INFO][2][AnalysisMeanStateSpace][et] RMSE scored using Collier2018
[INFO][2][confront][Evapotranspiration/GLEAMv3.3a][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][2][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [QVEGE] in the model results
[DEBUG][2][WorkConfront][Evapotranspiration/GLEAMv3.3a][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][4][AnalysisMeanStateSpace][albedo] Bias scored using Collier2018
[INFO][4][AnalysisMeanStateSpace][albedo] RMSE scored using Collier2018
[INFO][4][confront][Albedo/GEWEX.SRB][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][4][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rsds,FSDS] in the model results
[DEBUG][4][WorkConfront][Albedo/GEWEX.SRB][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 157, in confront
    obs, mod, obs_timeint, mod_timeint = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 64, in stageData
    dn_mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][6][MakeComparable][SurfaceNetLWRadiation/CERESed4.1][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Spatial data was clipped from the reference:  before: [228 360 720] after: [228 360 711]
[INFO][6][AnalysisMeanStateSpace][rlns] Bias scored using Collier2018
[INFO][5][AnalysisMeanStateSites][rsns] Bias scored using Collier2018
[INFO][3][AnalysisMeanStateSites][hfss] Bias scored using Collier2018
[INFO][5][AnalysisMeanStateSites][rsns] RMSE scored using Collier2018
[INFO][3][AnalysisMeanStateSites][hfss] RMSE scored using Collier2018
[INFO][5][confront][SurfaceNetSWRadiation/WRMC.BSRN][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][5][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rsns,FSA] in the model results
[DEBUG][5][WorkConfront][SurfaceNetSWRadiation/WRMC.BSRN][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][3][confront][SensibleHeat/FLUXNET2015][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][3][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [hfss,sh,FSH] in the model results
[DEBUG][3][WorkConfront][SensibleHeat/FLUXNET2015][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][6][AnalysisMeanStateSpace][rlns] RMSE scored using Collier2018
[INFO][6][confront][SurfaceNetLWRadiation/CERESed4.1][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][6][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FIRE] in the model results
[DEBUG][6][WorkConfront][SurfaceNetLWRadiation/CERESed4.1][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][4][MakeComparable][SurfaceUpwardSWRadiation/CERESed4.1][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Spatial data was clipped from the reference:  before: [228 360 720] after: [228 360 711]
[INFO][4][AnalysisMeanStateSpace][rsus] Bias scored using Collier2018
[INFO][4][AnalysisMeanStateSpace][rsus] RMSE scored using Collier2018
[INFO][4][confront][SurfaceUpwardSWRadiation/CERESed4.1][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][4][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rsus,FSR] in the model results
[DEBUG][4][WorkConfront][SurfaceUpwardSWRadiation/CERESed4.1][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][5][MakeComparable][SurfaceUpwardLWRadiation/CERESed4.1][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Spatial data was clipped from the reference:  before: [228 360 720] after: [228 360 711]
[INFO][3][MakeComparable][SensibleHeat/FLUXCOM][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Spatial data was clipped from the reference:  before: [420 360 720] after: [420 360 711]
[INFO][5][AnalysisMeanStateSpace][rlus] Bias scored using Collier2018
[INFO][5][AnalysisMeanStateSpace][rlus] RMSE scored using Collier2018
[INFO][5][confront][SurfaceUpwardLWRadiation/CERESed4.1][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][5][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rlus,FIRE] in the model results
[DEBUG][5][WorkConfront][SurfaceUpwardLWRadiation/CERESed4.1][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][3][AnalysisMeanStateSpace][hfss] Bias scored using Collier2018
[INFO][3][AnalysisMeanStateSpace][hfss] RMSE scored using Collier2018
[INFO][3][confront][SensibleHeat/FLUXCOM][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][3][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [hfss,sh,FSH] in the model results
[DEBUG][3][WorkConfront][SensibleHeat/FLUXCOM][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][2][MakeComparable][Evapotranspiration/MODIS][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Spatial data was clipped from the reference:  before: [168 360 720] after: [168 360 711]
[INFO][4][AnalysisMeanStateSites][rsus] Bias scored using Collier2018
[INFO][4][AnalysisMeanStateSites][rsus] RMSE scored using Collier2018
[INFO][4][confront][SurfaceUpwardSWRadiation/FLUXNET2015][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][4][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rsus,FSR] in the model results
[DEBUG][4][WorkConfront][SurfaceUpwardSWRadiation/FLUXNET2015][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][2][AnalysisMeanStateSpace][et] Bias scored using Collier2018
[INFO][2][AnalysisMeanStateSpace][et] RMSE scored using Collier2018
[INFO][2][confront][Evapotranspiration/MODIS][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][2][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [QVEGE] in the model results
[DEBUG][2][WorkConfront][Evapotranspiration/MODIS][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][6][AnalysisMeanStateSites][rlns] Bias scored using Collier2018
[INFO][6][AnalysisMeanStateSites][rlns] RMSE scored using Collier2018
[INFO][6][confront][SurfaceNetLWRadiation/FLUXNET2015][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][6][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FIRE] in the model results
[DEBUG][6][WorkConfront][SurfaceNetLWRadiation/FLUXNET2015][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][3][MakeComparable][SensibleHeat/CLASS][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Spatial data was clipped from the reference:  before: [ 84 360 720] after: [ 84 360 711]
[INFO][7][AnalysisMeanStateSites][rns] Bias scored using Collier2018
[INFO][7][AnalysisMeanStateSites][rns] RMSE scored using Collier2018
[INFO][7][confront][SurfaceNetRadiation/FLUXNET2015][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][7][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FIRE] in the model results
[DEBUG][7][WorkConfront][SurfaceNetRadiation/FLUXNET2015][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][3][AnalysisMeanStateSpace][hfss] Bias scored using Collier2018
[INFO][3][AnalysisMeanStateSpace][hfss] RMSE scored using Collier2018
[INFO][3][confront][SensibleHeat/CLASS][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[INFO][4][MakeComparable][SurfaceUpwardSWRadiation/GEWEX.SRB][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Spatial data was clipped from the reference:  before: [288 360 720] after: [288 360 711]
[INFO][4][AnalysisMeanStateSpace][rsus] Bias scored using Collier2018
[INFO][4][AnalysisMeanStateSpace][rsus] RMSE scored using Collier2018
[INFO][4][confront][SurfaceUpwardSWRadiation/GEWEX.SRB][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][4][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [rsus,FSR] in the model results
[DEBUG][4][WorkConfront][SurfaceUpwardSWRadiation/GEWEX.SRB][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][6][MakeComparable][SurfaceNetLWRadiation/GEWEX.SRB][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Spatial data was clipped from the reference:  before: [288 360 720] after: [288 360 711]
[INFO][6][AnalysisMeanStateSpace][rlns] Bias scored using Collier2018
[INFO][6][AnalysisMeanStateSpace][rlns] RMSE scored using Collier2018
[INFO][6][confront][SurfaceNetLWRadiation/GEWEX.SRB][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][6][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [FIRE] in the model results
[DEBUG][6][WorkConfront][SurfaceNetLWRadiation/GEWEX.SRB][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][2][MakeComparable][Evapotranspiration/MOD16A2][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Spatial data was clipped from the reference:  before: [180 360 720] after: [180 360 711]
[INFO][2][AnalysisMeanStateSpace][et] Bias scored using Collier2018
[INFO][2][AnalysisMeanStateSpace][et] RMSE scored using Collier2018
[INFO][2][confront][Evapotranspiration/MOD16A2][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][2][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [QVEGE] in the model results
[DEBUG][2][WorkConfront][Evapotranspiration/MOD16A2][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][2][AnalysisMeanStateSites][hfls] Bias scored using Collier2018
[INFO][2][AnalysisMeanStateSites][hfls] RMSE scored using Collier2018
[INFO][2][confront][LatentHeat/FLUXNET2015][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
[DEBUG][2][extractTimeSeries][clm50_cesm23a02cPPEn08ctsm51d030] Could not find [hfls,le,EFLX_LH_TOT] in the model results
[DEBUG][2][WorkConfront][LatentHeat/FLUXNET2015][clm50_cesm23a02cPPEn08ctsm51d030]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/.local/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][6][AnalysisMeanStateSites][rlns] Bias scored using Collier2018
[INFO][6][AnalysisMeanStateSites][rlns] RMSE scored using Collier2018
[INFO][6][confront][SurfaceNetLWRadiation/WRMC.BSRN][ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist] Success
